In [105]:
import numpy as np
import tensorflow as tf

In [106]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [113]:
W = tf.Variable(tf.random.normal([3, 1], name='weight'))
b = tf.Variable(tf.random.normal([1,], name='bias'))

learning_rate = tf.Variable(0.00002)
optimizer = tf.keras.optimizers.SGD(learning_rate, momentum = 0.3)

def predict(X):
    return tf.matmul(X, W) + b

In [133]:
for i in range(2500):
    with tf.GradientTape(persistent=False) as tape:
        hypothesis = tf.matmul(x_data, W) + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
        W_grad, b_grad= tape.gradient(cost, [W, b])
#         optimizer.apply_gradients(zip(grads, [W, b]))
        W.assign_sub(learning_rate * W_grad)
        b.assign_sub(learning_rate * b_grad)
        
    if i % 50 == 0:
        print("epochs: {:5} |cost: {:10.6} |W1: {:10.4} |W2: {:10.4} |W3: {:10.4} | b: {:10.6}"
              .format(i, cost, W.numpy()[0][0], W.numpy()[1][0], W.numpy()[2][0], b.numpy()[0]))
        

epochs:     0 |cost:   0.675447 |W1:      1.019 |W2:     0.6341 |W3:     0.3796 | b:   -1.77229
epochs:    50 |cost:   0.672968 |W1:       1.02 |W2:     0.6343 |W3:     0.3784 | b:    -1.7724
epochs:   100 |cost:   0.670513 |W1:      1.021 |W2:     0.6344 |W3:     0.3773 | b:   -1.77251
epochs:   150 |cost:   0.668079 |W1:      1.022 |W2:     0.6346 |W3:     0.3761 | b:   -1.77261
epochs:   200 |cost:   0.665655 |W1:      1.023 |W2:     0.6347 |W3:      0.375 | b:   -1.77272
epochs:   250 |cost:   0.663261 |W1:      1.024 |W2:     0.6349 |W3:     0.3738 | b:   -1.77283
epochs:   300 |cost:   0.660882 |W1:      1.025 |W2:      0.635 |W3:     0.3727 | b:   -1.77294
epochs:   350 |cost:   0.658518 |W1:      1.026 |W2:     0.6352 |W3:     0.3715 | b:   -1.77304
epochs:   400 |cost:   0.656177 |W1:      1.027 |W2:     0.6353 |W3:     0.3704 | b:   -1.77315
epochs:   450 |cost:   0.653847 |W1:      1.028 |W2:     0.6354 |W3:     0.3693 | b:   -1.77326
epochs:   500 |cost:   0.651545 |W1:    

In [137]:
print(W.numpy())
print(x_data)
print(y_data)

[[1.0660331 ]
 [0.6417609 ]
 [0.32607526]]
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [136]:
predict(x_data).numpy()

array([[151.83931],
       [184.16342],
       [180.84634],
       [196.06166],
       [141.22429],
       [102.17728]], dtype=float32)

In [138]:
predict([[89., 95., 92], [11, 35, 85]]).numpy()

array([[184.06555 ],
       [ 60.126774]], dtype=float32)