In [4]:
import tensorflow as tf
import numpy as np

In [7]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
tf.print(t)
print(t.ndim)
print(t.shape)
print(t[0], t[-1])
print(t[2:5], t[4:-1])
print(t[:2])

array([0., 1., 2., 3., 4., 5., 6.])
1
(7,)
0.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.]


In [10]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
tf.print(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


In [13]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.print(t)
tf.shape(t)

[[[[1 2 3 4]
   [5 6 7 8]
   [9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]]


<tf.Tensor: id=10, shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [16]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2)

<tf.Tensor: id=19, shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

In [17]:
# Broadcasting
(matrix1*matrix2)

<tf.Tensor: id=20, shape=(2, 2), dtype=float32, numpy=
array([[6., 6.],
       [6., 6.]], dtype=float32)>

In [20]:
# Reducemean
x = [[1., 2.],
     [3., 4.]]


print(tf.reduce_mean(x, axis=0))
print(tf.reduce_mean(x, axis=1))
print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)))


tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)


In [22]:
# Argmax
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.argmax(x, axis=0))
print(tf.argmax(x, axis=1))

tf.Tensor([1 0 0], shape=(3,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)


In [23]:
# Reshape
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [24]:
tf.reshape(t, shape=[-1, 3])

<tf.Tensor: id=55, shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])>

In [25]:
tf.reshape(t, shape=[-1, 3])

<tf.Tensor: id=58, shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])>

In [27]:
# squeeze
tf.squeeze([[0], [1], [2]])
# expand
tf.expand_dims([0, 1, 2], 1)


<tf.Tensor: id=65, shape=(3, 1), dtype=int32, numpy=
array([[0],
       [1],
       [2]])>

In [29]:
# one hot
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3])

<tf.Tensor: id=77, shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)>

In [31]:
# casting
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32)
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32)

<tf.Tensor: id=83, shape=(4,), dtype=int32, numpy=array([1, 0, 1, 0])>

In [35]:
# stack
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z])

print(tf.stack([x, y, z], axis=1))
print(tf.stack([x, y, z], axis=0))


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [36]:
# one and zeros like
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x)

<tf.Tensor: id=107, shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [37]:
tf.zeros_like(x)

<tf.Tensor: id=109, shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [38]:
# zip
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)
    
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4
2 5
3 6
1 4 7
2 5 8
3 6 9


In [41]:
# transpose
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
tf.print(t.shape)
tf.print(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [46]:
t1 = tf.transpose(t, [1, 0, 2])   # i=0, j=1, k=2   ==> i j k -> j i k transpose
tf.print(t1)
t1.shape

[[[0 1 2]
  [6 7 8]]

 [[3 4 5]
  [9 10 11]]]


TensorShape([2, 2, 3])

In [47]:
t2 = tf.transpose(t, [1, 2, 0]) # i j k -> j k i transpose
tf.print(t2)
t1.shape

[[[0 6]
  [1 7]
  [2 8]]

 [[3 9]
  [4 10]
  [5 11]]]


TensorShape([2, 2, 3])